-- Таблица категорий
CREATE TABLE "categories" (
    "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category_name" varchar NOT NULL,
    "parent_id" integer,
    "attribute_schema" jsonb DEFAULT '{}',
    "created_at" timestamp DEFAULT now(),
    "active" bool DEFAULT true,
    "updated_at" timestamp DEFAULT now(),
    "deleted_at" timestamp
);

-- Таблица товаров
CREATE TABLE "products" (
    "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_name" varchar NOT NULL,
    "product_description" varchar,
    "price" decimal(10,2) CHECK (price >= 0), -- Изменено на >= 0
    "category_id" integer NOT NULL,
    "user_id" integer NOT NULL,
    "attributes" jsonb DEFAULT '{}',
    "created_at" timestamp DEFAULT now(),
    "active" bool DEFAULT true,
    "updated_at" timestamp DEFAULT now(),
    "deleted_at" timestamp
);

-- Таблица вариантов товаров
CREATE TABLE "product_variants" (
    "variant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" integer NOT NULL,
    "sku" varchar(50) UNIQUE NOT NULL,
    "price" decimal(10,2) NOT NULL CHECK (price >= 0), -- Изменено на >= 0
    "attributes" jsonb DEFAULT '{}',
    "stock" integer DEFAULT 0 CHECK (stock >= 0),
    "created_at" timestamp DEFAULT now(),
    "active" bool DEFAULT true,
    "updated_at" timestamp DEFAULT now(),
    "deleted_at" timestamp
);

-- Внешние ключи
ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("category_id") ON DELETE SET NULL;
ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id") ON DELETE RESTRICT;
ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON DELETE CASCADE;

-- Триггер для updated_at
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_categories_timestamp
    BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER update_products_timestamp
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER update_product_variants_timestamp
    BEFORE UPDATE ON product_variants
    FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- Индексы
CREATE INDEX idx_products_deleted_at ON products (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_categories_deleted_at ON categories (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_product_variants_deleted_at ON product_variants (deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_products_active ON products (active);
CREATE UNIQUE INDEX idx_categories_name_parent ON categories (category_name, parent_id) WHERE deleted_at IS NULL; -- Удален дубликат
CREATE INDEX idx_product_variants_product_id ON product_variants (product_id);
CREATE INDEX idx_product_variants_attributes ON product_variants USING GIN (attributes);
CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_user_id ON products (user_id);
CREATE INDEX idx_product_variants_stock ON product_variants (stock);

-- Комментарии
COMMENT ON TABLE categories IS 'Таблица для хранения категорий товаров';
COMMENT ON TABLE products IS 'Таблица для хранения информации о товарах маркетплейса';
COMMENT ON TABLE product_variants IS 'Таблица для хранения вариантов товаров (например, размеры, цвета)';