  app:
    name: 'ngMarketplace'
    version: '1.0.0'

  http:
    port: '9090'
    read-timeout: '10s'
    write-timeout: '10s'
    cors:
      debug: true
      allowed-methods: [ "GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE" ]
      allowed-origins: [ "*" ]
      allow-credentials: true
      allowed-headers:
        - "Authorization"
        - "Location"
        - "Charset"
        - "Access-Control-Allow-Origin"
        - "Content-Type"
        - "Origin"
        - "Accept"
        - "Content-Length"
        - "Accept-Encoding"
        - "X-CSRF-Token"
      options-passthrough: false
      exposed-headers:
        - "Location"
        - "Authorization"
        - "Content-Disposition"

  logger:
    log_level: 'debug'

  postgres:
    pool_max: 2
    db_source: postgres://marketplace:marketplace@localhost:5432/marketplace_ng