jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Устанавливаем docker-compose
      - name: Install Docker Compose
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-~/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64  -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

      - name: Verify Docker Compose installation
        run: |
          docker compose version

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 10
          docker-compose -f docker-compose.yml logs

      - name: Check application health
        run: |
          curl --fail --retry 3 --retry-delay 5 http://localhost:8081 || exit 1

      - name: Stop Docker Compose
        run: |
          docker-compose -f docker-compose.yml down