name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub (optional, only if you push images)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and start services with Docker Compose
      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 10  # Wait for services to start
          docker-compose -f docker-compose.yml logs  # Output logs for debugging

      # Verify the application is running
      - name: Check application health
        run: |
          curl --fail --retry 3 --retry-delay 5 http://localhost:8081 || exit 1

      # Stop and remove Docker Compose services
      - name: Stop Docker Compose
        run: |
          docker-compose -f docker-compose.yml down